export const QUESTIONS = [
  {
    id: 4,
    text: "How many years have you been doing work that involved planning, coordinating, or leading?",
    options: ["Just starting (< 1 year)", "1-2 years", "3-5 years", "6-10 years", "10+ years"],
    scores: [0, 20, 40, 60, 80],
  },
  {
    id: 5,
    text: "What's the largest scale of work you've coordinated or been responsible for?",
    options: [
      "Individual contributor",
      "Small team/project (< 5 people / < $100K)",
      "Led team ($100K-$1M / 5-15 people)",
      "Significant initiatives ($1M-$5M / 15-30 people)",
      "Large programs ($5M+ / 30+ people)",
    ],
    scores: [0, 20, 40, 60, 80],
  },
  {
    id: 6,
    text: "How comfortable are you creating plans, timelines, and schedules? (e.g., project schedules, event timelines, ticketing workflows)",
    options: ["Not experienced", "Somewhat familiar", "Competent", "Very confident", "Expert"],
    scores: [0, 25, 50, 75, 100],
  },
  {
    id: 7,
    text: "How comfortable managing budgets and business metrics? (e.g., ROI, customer lifetime value, cost per resolution, vendor negotiations)",
    options: ["Never involved", "Basic awareness", "Can manage", "Strong background", "Expert"],
    scores: [0, 20, 40, 70, 100],
  },
  {
    id: 8,
    text: "How often do you anticipate problems and create backup plans? (e.g., handling escalations, contingency planning, reducing downtime)",
    options: ["Rarely", "Sometimes", "Often", "Frequently", "Always"],
    scores: [0, 20, 40, 70, 100],
  },
  {
    id: 9,
    text: "How much have you improved how work gets done? (e.g., reducing ticket backlog, streamlining workflows, automating tasks)",
    options: ["Haven't focused", "Identified but didn't implement", "Small improvements", "Regularly improve", "Redesigned major systems"],
    scores: [0, 20, 40, 70, 100],
  },
  {
    id: 10,
    text: "How much experience leading or influencing others? (e.g., managing teams, mentoring, vendor management, coaching)",
    options: ["Individual contributor", "Influenced 1-3 informally", "Led 4-8 people", "Managed 9-15 people", "Led 15+ people"],
    scores: [0, 25, 50, 75, 100],
  },
  {
    id: 11,
    text: "How comfortable communicating with different audiences? (e.g., presentations, customer communication, handling escalations)",
    options: ["Prefer independence", "Within immediate team", "Across departments", "Present to leadership", "Expert stakeholder management"],
    scores: [0, 25, 50, 75, 100],
  },
  {
    id: 12,
    text: "How often worked across departments/organizations? (e.g., vendor coordination, cross-team escalations, partnerships)",
    options: ["Alone with my team", "Occasionally with others", "Regularly coordinate", "Frequently cross-functional", "Complex stakeholder ecosystems"],
    scores: [0, 25, 50, 75, 100],
  },
  {
    id: 13,
    text: "How do you handle difficult interpersonal situations? (Support: diffusing escalations; Events: vendor disputes; Tech: team disagreements)",
    options: ["Avoid conflict", "Direct but awkward", "Professional & diplomatic", "Turn conflict into collaboration", "Excel at building trust"],
    scores: [0, 25, 50, 75, 100],
  },
  {
    id: 14,
    text: "How do you make decisions with incomplete information? (e.g., technical choices, issue resolution, vendor selection)",
    options: ["Need clear direction", "Can decide with support", "Comfortable with judgment calls", "Strong analytical & intuitive", "Expert synthesizing complex info"],
    scores: [0, 25, 50, 75, 100],
  },
  {
    id: 15,
    text: "How do you handle competing demands & scope creep? (e.g., saying no diplomatically, ruthless prioritization, protecting capacity)",
    options: ["Take everything on", "Try to say yes, overwhelmed", "Set boundaries, not strategic", "Strong at saying no diplomatically", "Expert at ruthless prioritization"],
    scores: [0, 25, 50, 75, 100],
  },
  {
    id: 16,
    text: "How do you respond when plans fall apart? (e.g., system failures, escalations, venue changes, deadlines missed)",
    options: ["Stressed & difficult", "Need time to adjust", "Can adapt, prefer stability", "Embrace change, calm under pressure", "Thrive in uncertainty"],
    scores: [0, 25, 50, 75, 100],
  },
  {
    id: 17,
    text: "How comfortable learning & using new software tools? (e.g., PM tools, support platforms, event software, CRM)",
    options: ["Resist new tools", "Can learn with support", "Comfortable picking up", "Quick learner", "Early adopter"],
    scores: [0, 20, 50, 75, 100],
  },
  {
    id: 18,
    text: "How comfortable with data & analytics? (e.g., Excel, dashboards, metrics, support data, event analytics, KPIs)",
    options: ["Avoid data", "Read reports others create", "Create reports & analysis", "Create dashboards & analysis", "Expert with SQL & analytics"],
    scores: [0, 20, 40, 70, 100],
  },
  {
    id: 19,
    text: "How experienced with AI & automation? (e.g., ChatGPT, automation platforms, workflow automation)",
    options: ["Never used", "Aware but haven't tried", "Tried once or twice", "Occasionally use", "Regularly integrate"],
    scores: [0, 20, 50, 75, 100],
  },
  {
    id: 20,
    text: "How deep is your expertise in your primary industry?",
    options: ["New / < 2 years", "Developing / 2-5 years", "Experienced / 5-10 years", "Deep expertise / 10-15 years", "Industry veteran / 15+ years"],
    scores: [10, 30, 50, 70, 90],
  },
  {
    id: 21,
    text: "How many different industries have you worked in?",
    options: ["One industry", "Two industries", "Three industries", "Four or more"],
    scores: [20, 20, 20, 20],
  },
  {
    id: 22,
    text: "PM methodologies you're familiar with? (Select all that apply)",
    options: ["Agile / Scrum", "Waterfall / Traditional", "Project Management", "Program / Portfolio", "Operations Management", "Product Management"],
    scores: [15, 15, 15, 15, 15, 15],
    multiple: true,
  },
  {
    id: 23,
    text: "What's driving your interest in PM?",
    options: ["Exploring career change", "Lateral move into PM", "Advancement opportunity", "Clear progression path", "C-level ambitions"],
    scores: [20, 40, 60, 80, 100],
  },
  {
    id: 24,
    text: "How do you approach learning new skills & taking on new types of work?",
    options: ["Hesitant, prefer comfort zone", "Need support", "Self-directed", "Eager learner", "Growth mindset always"],
    scores: [0, 40, 70, 85, 100],
  },
];

export const ROLES = [
  "Software Engineer / Developer",
  "Operations Coordinator / Analyst",
  "Sales / Account Manager",
  "Product Manager / Product Owner",
  "Business Analyst",
  "Project Coordinator",
  "Team Lead / Supervisor",
  "Manager (non-PM)",
  "Consultant",
  "Entrepreneur / Freelancer",
  "Events Manager / Event Coordinator",
  "Customer Support / Support Manager",
  "Customer Success Manager",
  "Customer Experience (CX) Manager",
  "Service Manager / Operations Support",
  "Other",
];

export const INDUSTRIES = [
  "Operations & Business Services",
  "IT / Software / Technology",
  "Construction / Real Estate",
  "Healthcare",
  "Finance / Banking",
  "Manufacturing",
  "Consulting",
  "E-commerce / Retail",
  "Education",
  "Nonprofit / Government",
  "Customer Service / Customer Experience",
  "Events / Hospitality / Travel",
  "Other",
];

export const TRANSFERABLE_SKILLS = [
  "Planning & Organization",
  "Leadership & Influence",
  "Communication",
  "Problem-Solving",
  "Process Management",
  "Financial Management",
  "Data Analysis",
  "Stakeholder Management",
];
